# demo_qwen_integration.py

import os
import sys
sys.path.append('src')

from auth_system import VocalPulseAuth
import numpy as np

def demo_qwen_full():
    """
    Complete demo of VocalPulse + Qwen 2.5 integration
    """
    
    print("=" * 70)
    print("VocalPulse + Qwen 2.5 7B Integration Demo")
    print("Featherless AI-powered voice biometric analysis")
    print("=" * 70)
    
    # Check API key
    if not os.getenv("FEATHERLESS_API_KEY"):
        print("\n❌ Set FEATHERLESS_API_KEY in .env file")
        print("Get key from: https://featherless.ai/")
        return
    
    # Initialize with Qwen analyst
    auth = VocalPulseAuth(use_ai_analyst=True, language="english")
    
    # Generate test audio (human-like with tremor)
    print("\n[1] Generating test audio with 8-12 Hz tremor...")
    sr = 16000
    t = np.linspace(0, 3, sr * 3)
    
    # Base speech
    base = np.sin(2 * np.pi * 150 * t)
    # Add 10.5 Hz physiological tremor
    tremor = 0.05 * np.sin(2 * np.pi * 10.5 * t)
    # Add breathing modulation
    breath = 0.3 * np.sin(2 * np.pi * 0.2 * t)
    
    human_audio = base * (1 + tremor) * (1 + breath)
    human_audio = human_audio / np.max(np.abs(human_audio))
    
    # Add neural precursor (200ms pre-speech)
    precursor = np.zeros_like(human_audio)
    precursor[1600:3200] = 0.01 * np.sin(2 * np.pi * 10.5 * t[1600:3200])
    human_audio = human_audio + precursor
    
    print("   ✓ Test audio created with physiological signals")
    
    # Test 1: Full analysis with Qwen explanation
    print("\n[2] Analyzing with Qwen AI explanation...")
    result = auth.authenticate_full("demo_user", human_audio)
    
    print(f"\n   🔬 BIOMARKER RESULTS:")
    print(f"      Tremor: {result['biomarkers']['tremor']['is_human']} "
          f"(score: {result['biomarkers']['tremor']['score']:.2f})")
    print(f"      Respiratory: {result['biomarkers']['respiratory']['is_human']}")
    print(f"      Precursor: {result['biomarkers']['precursor']['is_live_human']}")
    print(f"      Overall: {result['verdict']} "
          f"(confidence: {result['authenticity_score']:.1%})")
    
    print(f"\n   🤖 QWEN AI EXPLANATION:")
    print(f"      {result.get('ai_explanation', 'N/A')[:200]}...")
    
    if 'ai_structured' in result:
        s = result['ai_structured']
        print(f"\n   📊 STRUCTURED INSIGHT:")
        print(f"      Verdict: {s.get('verdict_summary')}")
        print(f"      Evidence: {s.get('key_evidence')}")
        print(f"      Confidence: {s.get('confidence_level')}")
    
    # Test 2: Smart challenge generation
    print("\n[3] Generating AI-powered challenge...")
    challenge = auth.get_smart_challenge(difficulty="medium")
    
    print(f"\n   🎯 CHALLENGE (generated by Qwen):")
    print(f"      Text: {challenge.get('challenge_text')}")
    print(f"      Expected delay: {challenge.get('expected_delay_ms')} ms")
    print(f"      Cognitive load: {challenge.get('cognitive_load')}")
    print(f"      Why effective: {challenge.get('why_effective', 'N/A')[:100]}...")
    
    # Test 3: Synthetic detection with fraud analysis
    print("\n[4] Testing synthetic audio detection...")
    # Perfect sine wave (no tremor)
    synthetic = np.sin(2 * np.pi * 150 * t)
    synthetic = synthetic / np.max(np.abs(synthetic))
    
    result_synth = auth.authenticate_full("demo_user", synthetic)
    
    print(f"\n   🔬 SYNTHETIC RESULTS:")
    print(f"      Verdict: {result_synth['verdict']}")
    print(f"      Confidence: {result_synth['authenticity_score']:.1%}")
    
    if 'fraud_intelligence' in result_synth:
        f = result_synth['fraud_intelligence']
        print(f"\n   🚨 FRAUD INTELLIGENCE (Qwen-powered):")
        print(f"      Analysis: {f['fraud_analysis'][:150]}...")
        print(f"      Severity: {f['severity']}")
        print(f"      Action: {f['recommended_action']}")
    
    # Test 4: Multilingual (Tamil)
    print("\n[5] Testing Tamil language support...")
    auth_tamil = VocalPulseAuth(use_ai_analyst=True, language="tamil")
    result_tamil = auth_tamil.authenticate_full("tamil_user", human_audio)
    
    print(f"\n   🇮🇳 TAMIL EXPLANATION:")
    print(f"      {result_tamil.get('ai_explanation', 'N/A')[:150]}...")
    
    print("\n" + "=" * 70)
    print("✅ Qwen 2.5 integration complete!")
    print("Features demonstrated:")
    print("   • Biomarker analysis with AI explanation")
    print("   • Smart challenge generation")
    print("   • Fraud intelligence reporting")
    print("   • Multilingual support (Tamil/Malayalam)")
    print("=" * 70)

if __name__ == "__main__":
    demo_qwen_full()